# Generated by Django 2.2.28 on 2022-12-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresssgflfaospf'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresssgflfaospf',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
